language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"

matrix:
  exclude:
    - env: "RAILS_VERSION=3.2.0"
      rvm: 2.2
